version: '3.8'
services:
  jquerysite:
    depends_on:
      - jquerydb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jquerysite
    environment:
      - WORDPRESS_DB_HOST=jquerydb:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
    volumes:
      - ./jquery-wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads:rw
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./apache/.htaccess:/var/www/html/.htaccess
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${JQUERY_WP_HTTP_PORT:-9412}:80"
    networks:
      - jquerynet

  jquerydb:
    image: mariadb:10.11
    container_name: jquerydb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - jquerydbdata:/var/lib/mysql
    ports:
      - "${JQUERY_WP_MYSQL_PORT:-9414}:3306"
    networks:
      - jquerynet

volumes:
  jquerydbdata:

networks:
  jquerynet:
    driver: bridge
